# MEXC Data Collector 設定ファイル

# MEXC API設定
mexc:
    # 本番環境（MEXCにはテストネットがないため本番環境を使用）
    production:
        # WebSocket URL
        ws_url: "wss://contract.mexc.com/edge"
        # REST API URL（将来の拡張用）
        api_url: "https://api.mexc.com"

    # 使用環境（常に"production"）
    environment: "production"

    # WebSocket再接続設定
    reconnect_interval: 5
    max_reconnect_attempts: 10
    ping_interval: 20

# データ管理設定
data:
    # ティックデータ保持時間（時間）- メモリ内一時保存用
    tick_data_retention_hours: 1

# QuestDB設定
questdb:
    host: "questdb"
    port: 9000
    ilp_port: 9009

    # テーブル名
    tick_table: "tick_data"

# ログ設定
logging:
    level: "INFO"
    file: "data_collector.log"
    max_size_mb: 10
    backup_count: 5
